[lint]
# Enable all `pydocstyle` rules, limiting to those that adhere to the
# Google convention via `convention = "google"`, below.
select = ["D"]

# On top of the Google convention, disable `D417`, which requires
# documentation for every function parameter.
ignore = ["D417"]

[lint.pydocstyle]
convention = "google"

# https://docs.astral.sh/ruff/settings/#lintpydocstyle
# NOTE: Can be added to a pyproject.toml file if desired. Kept separate for now.
